version: '3.8'

services:
  frontend:
    build:
      context: ./task-tracker
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    depends_on:
      - backend

  backend:
    build:
      context: ./task-tracker-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./task-tracker-api/database.sqlite:/app/database.sqlite
